/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base$view.demo',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo',
      icon: 'mdi:flask-outline',
      order: 99,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'mdi:shield-account-outline',
      order: 2
    },
    children: [
      {
        name: 'manage_admin',
        path: '/manage/admin',
        component: 'view.manage_admin',
        meta: {
          title: 'manage_admin',
          i18nKey: 'route.manage_admin',
          icon: 'mdi:account-tie-outline',
          order: 1
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'mdi:account-group-outline',
      order: 3
    },
    children: [
      {
        name: 'user_list',
        path: '/user/list',
        component: 'view.user_list',
        meta: {
          title: 'user_list',
          i18nKey: 'route.user_list',
          icon: 'mdi:account-outline',
          order: 1
        }
      },
      {
        name: 'user_role',
        path: '/user/role',
        component: 'view.user_role',
        meta: {
          title: 'user_role',
          i18nKey: 'route.user_role',
          icon: 'mdi:account-key-outline',
          order: 2
        }
      }
    ]
  },
  {
    name: 'points',
    path: '/points',
    component: 'layout.base',
    meta: {
      title: 'points',
      i18nKey: 'route.points',
      icon: 'mdi:circle-multiple-outline',
      order: 4
    },
    children: [
      {
        name: 'points_settings',
        path: '/points/settings',
        component: 'view.points_settings',
        meta: {
          title: 'points_settings',
          i18nKey: 'route.points_settings',
          icon: 'mdi:tune-variant',
          order: 1
        }
      },
      {
        name: 'points_records',
        path: '/points/records',
        component: 'view.points_records',
        meta: {
          title: 'points_records',
          i18nKey: 'route.points_records',
          icon: 'mdi:text-box-outline',
          order: 2
        }
      }
    ]
  }
];
